In [3]:
import pandas as pd
df = pd.read_csv("sample_data.csv")

In [4]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,US-2023-103800,1/3/2023,1/7/2023,Standard Class,DP-13000,Darren Powers,Consumer,United States,Houston,...,77095,Central,OFF-PA-10000174,Office Supplies,Paper,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",16.448,2.0,0.2,5.5512
1,2,US-2023-112326,1/4/2023,1/8/2023,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-BI-10004094,Office Supplies,Binders,GBC Standard Plastic Binding Systems Combs,3.540,2.0,0.8,-5.4870
2,3,US-2023-112326,1/4/2023,1/8/2023,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-LA-10003223,Office Supplies,Labels,Avery 508,11.784,3.0,0.2,4.2717
3,4,US-2023-112326,1/4/2023,1/8/2023,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-ST-10002743,Office Supplies,Storage,SAFCO Boltless Steel Shelving,272.736,3.0,0.2,-64.7748
4,5,US-2023-141817,1/5/2023,1/12/2023,Standard Class,MB-18085,Mick Brown,Consumer,United States,Philadelphia,...,19143,East,OFF-AR-10003478,Office Supplies,Art,Avery Hi-Liter EverBold Pen Style Fluorescent ...,19.536,3.0,0.2,4.8840

In [6]:
df.shape

(4589, 21)

In [7]:
df.describe()

            Row ID         Sales     Quantity     Discount       Profit
count  4589.000000   4588.000000  4588.000000  4588.000000  4588.000000
mean   2295.000000    234.396218     3.796861     0.154385    27.411884
std    1324.874522    624.736886     2.233613     0.206002   193.845897
min       1.000000      0.852000     1.000000     0.000000 -3701.892800
25%    1148.000000     17.407500     2.000000     0.000000     1.678200
50%    2295.000000     56.300000     3.000000     0.150000     8.879200
75%    3442.000000    216.660000     5.000000     0.200000    31.276000
max    4589.000000  22638.480000    14.000000     0.800000  4630.475500

In [9]:
df.mean(numeric_only=True)
df.median(numeric_only=True)
df.std(numeric_only=True)
df.var(numeric_only=True)
df.mode()
df.corr(numeric_only=True)

            Row ID     Sales  Quantity  Discount    Profit
Row ID    1.000000 -0.002058  0.003102 -0.004868  0.012997
Sales    -0.002058  1.000000  0.207830 -0.018482  0.323763
Quantity  0.003102  0.207830  1.000000  0.004263  0.059615
Discount -0.004868 -0.018482  0.004263  1.000000 -0.261937
Profit    0.012997  0.323763  0.059615 -0.261937  1.000000